default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Donzioo@2024
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: mksurveyconstruction_development

test:
  <<: *default
  database: mksurveyconstruction_test

production:
  <<: *default
  database: mksurveyconstruction_production
  username: mksurveyconstruction
  password: <%= ENV["MKSURVEYCONSTRUCTION_DATABASE_PASSWORD"] %>
